name: 添加音乐来源
description: 添加音乐来源api
title: "[添加来源]"
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        在反馈问题前，请确保本插件是在最新版。
  - type: textarea
    id: main_link
    attributes:
      label: 音乐来源，官网链接
      description: 最好是提供API项目链接/API相关文章
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: 为什么要添加这个来源
      description: 它有什么独特之处或者独有版权？
    validations:
      required: true
  - type: checkboxes
    attributes: 
      label: 提交前我已确定：
      options: 
        - label: 我已阅读README，没有发现对应内容。
          required: true
        - label: 我已在issue内搜索，没有发现已有的issue。
          required: true
